export enum WordsThemes {
    acquaintanceNumbers = 'acquaintanceNumbers',
    coloursShapes = 'coloursShapes',
    familyHome = 'familyHome',
    gamesHobbies = 'gamesHobbies',
    clothesWeather = 'clothesWeather',
    food = 'food',
    travel = 'travel',
    animals = 'animals',
    human = 'human',
    time = 'time',
    holidays = 'holidays',
    school = 'school',
    nature = 'nature',
    cityLife = 'cityLife',
    professions = 'professions',
    feelings = 'feelings',
    shopping = 'shopping',
    rules = 'rules',
    lifeStyle = 'lifeStyle',
    inventions = 'inventions',
    socialNets = 'socialNets',
    health = 'health',
    moviesSeries = 'moviesSeries'
}